posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.list_posts, name='index'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('category/<int:category_id>/', views.detail_category, name='category'),
]

rainn_bookshelf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField()
    rating = models.CharField(max_length=255)
    image_url = models.URLField(max_length=200, null=True)
    review = models.TextField()

    def __str__(self):
        return f'{self.name} ({self.date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'date',
            'rating',
            'image_url',
            'review',
        ]
        labels = {
            'name': 'Name',
            'date' : 'Date',
            'rating' : 'Rating',
            'image_url' : 'Image URL',
            'review' : 'Review',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'date',
        ]
        labels = {
            'author': 'User',
            'text': 'Comment',
            'date': 'Date'
        }

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.views import generic

def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)

def list_posts(request):
    post_list = Post.objects.all()
    context = {'post_list': post_list}
    return render(request, 'posts/index.html', context)

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_name = form.cleaned_data['name']
            post_date = form.cleaned_data['date']
            post_rating = form.cleaned_data['rating']
            post_image_url = form.cleaned_data['image_url']
            post_review = form.cleaned_data['review']
            post = Post(name=post_name,
                        date=post_date,
                        rating = post_rating,
                        image_url=post_image_url,
                        review = post_review)
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))

    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'posts/create.html', context)


def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.name = form.cleaned_data['name']
            post.date = form.cleaned_data['date']
            post.rating = form.cleaned_data['rating']
            post.image_url = form.cleaned_data['image_url']
            post.review = form.cleaned_data['review']
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))

    else:
        form = PostForm(
            initial={
                'name': post.name,
                'date': post.date,
                'rating': post.rating, 
                'image_url': post.image_url,
                'review': post.review
            })

    context = {'post': post,'form':form}
    return render(request, 'posts/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))

    context = {'post': post}
    return render(request, 'posts/delete.html', context)


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment_date = form.cleaned_data['date']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            date = comment_date,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categories.html'

def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'posts/category.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}
<h2>Categories</h2>
{% if category_list %}
<section>
    {% for category in category_list %}
    <ul>
        <a href="{% url 'posts:category' category.id %}">{{category.name}}</a>
    </ul>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma category.</p>
{% endif %}



{% endblock content %}

posts/templates/posts/category.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>{{category.name}}</h2>
<section class="lista-de-cards">
    {% for post in category.posts.all %}
    <article class="card">
        <p class = "post-title">{{ post.name }} ({{ post.rating }})</p>
        <p> ({{ post.date | date:"DATETIME_FORMAT" }}) </p>
        <section class = "review-image">
            <a  style="float:left"; href="{% url 'posts:detail' post.id %}"><img src="{{ post.image_url }}"
                alt="Poster do filme {{ post.name}}"> </a>
            <p class = "review-text"; style = "float:right";> {{ post.review }} </p>
        </section>
    </article>
    {% endfor %}
</section>



{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comment the review of {{ post.name }} </h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Comment</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Return to the review</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>New Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete "{{ post.name }}"?
    </p>
    <button type="submit">Delete</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.release_year }}
{% endblock title %}

{% block content %}
<section class = 'detail-title'>
    <h2>Review of {{ post.name }}</h2>
    <a href="{% url 'posts:update' post.id %}">Edit</a>
</section>

<section class="dados-de-post">
    <img src="{{ post.image_url }}" alt="Poster do post {{ post.name}}">
    <ul>
        <h2> Rating : {{post.rating}}</h2>
        <li> Review published: {{ post.date }} </li>
        {% if post.category_set.all %}
            <li>Categories: {{ post.category_set.all|join:", " }}</li>
        {% endif %}
        <hr>
        <li> 
            <p class = 'detail-review'>{{post.review}}</p>
        </li>
    </ul>
</section>

<section class = "update-delete">
    <ul>
        <li><a href="{% url 'posts:delete' post.id %}">Delete</a></li>
    </ul>
</section>

<section  class = 'com'>
    <header>
        <h3>Comments</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure class = 'comment'>
                    <hr>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}; {{ comment.date }}
                </figure>
            {% endfor %}
        {% else %}
            <p>No comments yet</p>
        {% endif %}
    </ul>
</section>

<a href="{% url 'posts:comment' post.pk %}"><button>Write your comment!</button></a>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Reviews</h2>
<section>
    <p>Find a specific review: <a href="{% url 'posts:search' %}">Search review</a></p>
    <p>Want to write your own review? <a href="{% url 'posts:create' %}">Add Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <p class = "post-title">{{ post.name }} ({{ post.rating }})</p>
        <p> ({{ post.date | date:"DATETIME_FORMAT" }}) </p>
        <section class = "review-image">
            <a  style="float:left"; href="{% url 'posts:detail' post.id %}"><img src="{{ post.image_url }}"
                alt="Poster do filme {{ post.name}}"> </a>
            <p class = "review-text"; style = "float:right";> {{ post.review }} </p>
        </section>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Nome</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <p class = "post-title">{{ post.name }} ({{ post.rating }})</p>
        <p> ({{ post.date | date:"DATETIME_FORMAT" }}) </p>
        <section class = "review-image">
            <a style="float:left"; href="{% url 'posts:detail' post.id %}"><img src="{{ post.image_url }}"
                alt="Poster do filme {{ post.name}}"> </a>
            <p style="float:right;"> {{ post.review }} </p>
        </section>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Update Post {{ post.name }}</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | The greatest bookshelf!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'bookshelf.svg' %}"> </a>
        <h1> Rainn's Bookshelf </h1>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li> 
                <li><a href="{% url 'posts:categories' %}">Categories</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>About this site</h2>
<p> This site presents a collection of books I have read and my shared thoughts about them.</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>The Greatest Bookshelf</i></h1>
<p>Page destined to share the reviews I have written for the books I recently read.</p>
<h2>Hope some of these books interest you as well!</h2>
{% endblock content %}